In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [14]:
import pandas as pd

list = [1,2,3,4,5]

pd.Series(list)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
pd.DataFrame(list)

   0
0  1
1  2
2  3
3  4
4  5

In [8]:
pd.DataFrame([list,list,list])

   0  1  2  3  4
0  1  2  3  4  5
1  1  2  3  4  5
2  1  2  3  4  5

In [17]:
df = pd.DataFrame([list,list,list] , columns = ['A', 'B', 'C', 'D', 'E'])
print(df)

   A  B  C  D  E
0  1  2  3  4  5
1  1  2  3  4  5
2  1  2  3  4  5

In [16]:
type(df)

pandas.core.frame.DataFrame

In [18]:
df

   A  B  C  D  E
0  1  2  3  4  5
1  1  2  3  4  5
2  1  2  3  4  5

In [19]:
del(df)

In [20]:
df

NameError: name 'df' is not defined

To learn the entire documentation of fuction -> Press Shift + tab in pd.array()

To learn all functions supported by pandas library, press Tab in pd.

## Reading Data from a file and Data Analysis

In [13]:
import pandas as pd
data = pd.read_csv("googleplaystore.csv")
data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [5]:
data.head() #Displays first 5 rows by default

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [6]:
type(data)

pandas.core.frame.DataFrame

In [7]:
data.head(10) # Displays first 10 rows of data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up

In [8]:
data["App"] #Returns value of the given column

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: object

In [9]:
data.columns #Returns all column names

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [10]:
for i in data.columns:
    print(data[i][0])

Photo Editor & Candy Camera & Grid & ScrapBook
ART_AND_DESIGN
4.1
159
19M
10,000+
Free
0
Everyone
Art & Design
January 7, 2018
1.0.0
4.0.3 and up

In [12]:
type(data["App"]) 

# We can apply indexing of Series and not DataFrames, data[0] -> will throw error

pandas.core.series.Series

## Removing Null Values from Data

In [14]:
data.isnull() #Checks each cell if value is Null or not

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,False,False,False,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False,False,False,False
10838,False,False,True,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,False,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
data.isnull().sum() #Returns sum of all null values for each column

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [22]:
df = data.dropna() #Drop rows where values are null
df  #This dropped almost 15% of the dataset

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [23]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

## Data Analysis - Numeric Columns

In [25]:
df["Rating"]

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ...
10834    4.0
10836    4.5
10837    5.0
10839    4.5
10840    4.5
Name: Rating, Length: 9360, dtype: float64

### 1. Finding Average Rating

In [33]:
int(sum(df["Rating"]))/len(df["Rating"])

4.191773504273504

In [36]:
str(int(sum(df["Rating"]))/len(df["Rating"]))[:4]

'4.19'

In [38]:
float(str(int(sum(df["Rating"]))/len(df["Rating"]))[:4])

4.19

### 2. How many apps with Rating 5?

In [46]:
count = 0

for rating in df["Rating"]:
    if rating == 5.0:
        count += 1

print("There are",count, "applications with Rating - 5.")

There are 274 applications with Rating - 5.

### 3. Count of Apps having rating in range 4 and 4.5

In [45]:
count = 0

for rating in df["Rating"]:
    if rating >=4.0 and rating <= 4.5:
        count += 1

print("There are",count, "applications with Rating in range 4.0 - 4.5.")

There are 5446 applications with Rating in range 4.0 - 4.5.

### 4. Finding Average Reviews

In [48]:
sum = 0
avg = 0
for review in df["Reviews"]:
    sum += int(review)
    avg = sum/len(df["Reviews"])

print(avg)

514376.7052350427

## Data Analysis - Categorical Columns

### 1. Total Number of Categories

In [49]:
len(df["Category"].unique())

33

### 2. Total Number of Apps for a given Category

In [50]:
count = 0

for category in df["Category"]:
    if category == "ART_AND_DESIGN":
        count += 1
print("There are total", count, "applications in given Category")

There are total 61 applications in given Category

### 3. Total Types in dataset

In [51]:
len(df["Type"].unique())

2

In [53]:
df["Type"].unique()

array(['Free', 'Paid'], dtype=object)

### 4. Total number of Free and Paid Apps

In [55]:
free = 0

for apps in df["Type"]:
    if apps == "Free":
        free += 1

print("There are total", free, "Free Applications", end=' ')

paid = 0

for apps in df["Type"]:
    if apps == "Paid":
        paid += 1

print("& there are total", paid, "Paid Applications")

There are total 8715 Free Applications & there are total 645 Paid Applications

In [56]:
len(df["Type"]) - free

645

### 5. Percent of Free and Paid Applications

In [57]:
free / (free + paid) * 100

93.10897435897436

In [59]:
paid / (free + paid) * 100

6.891025641025641

### 6. Name all Content Ratings

In [60]:
df["Content Rating"].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

## Data Analysis - Automatic Categorical

### 1. Total number of Apps in each Category

In [66]:
categories  = {}
for category in df["Category"].unique():
    count = 0
    for apps in df["Category"]:
        if apps  == category:
            count += 1
            categories[category] = count

print(categories)

{'ART_AND_DESIGN': 61, 'AUTO_AND_VEHICLES': 73, 'BEAUTY': 42, 'BOOKS_AND_REFERENCE': 178, 'BUSINESS': 303, 'COMICS': 58, 'COMMUNICATION': 328, 'DATING': 195, 'EDUCATION': 155, 'ENTERTAINMENT': 149, 'EVENTS': 45, 'FINANCE': 323, 'FOOD_AND_DRINK': 109, 'HEALTH_AND_FITNESS': 297, 'HOUSE_AND_HOME': 76, 'LIBRARIES_AND_DEMO': 64, 'LIFESTYLE': 314, 'GAME': 1097, 'FAMILY': 1746, 'MEDICAL': 350, 'SOCIAL': 259, 'SHOPPING': 238, 'PHOTOGRAPHY': 317, 'SPORTS': 319, 'TRAVEL_AND_LOCAL': 226, 'TOOLS': 733, 'PERSONALIZATION': 312, 'PRODUCTIVITY': 351, 'PARENTING': 50, 'WEATHER': 75, 'VIDEO_PLAYERS': 160, 'NEWS_AND_MAGAZINES': 233, 'MAPS_AND_NAVIGATION': 124}

### 2. Total number of Apps in each Type

In [65]:
types = {}
for name in df["Type"].unique():
    count = 0
    for apps in df["Type"]:
        if apps  == name:
            count += 1
            types[name] = count

print(types)

{'Free': 8715, 'Paid': 645}

### 3. Total Number of Apps for each Content Rating

In [67]:
types = {}
for name in df["Content Rating"].unique():
    count = 0
    for apps in df["Content Rating"]:
        if apps  == name:
            count += 1
            types[name] = count

print(types)

{'Everyone': 7414, 'Teen': 1084, 'Everyone 10+': 397, 'Mature 17+': 461, 'Adults only 18+': 3, 'Unrated': 1}

In [68]:
df["Rating"].describe()

count    9360.000000
mean        4.191838
std         0.515263
min         1.000000
25%         4.000000
50%         4.300000
75%         4.500000
max         5.000000
Name: Rating, dtype: float64

In [69]:
df["Type"].describe()

count     9360
unique       2
top       Free
freq      8715
Name: Type, dtype: object

In [70]:
df["Category"].describe()

count       9360
unique        33
top       FAMILY
freq        1746
Name: Category, dtype: object

## Handling Null Values - Numeric

In [102]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
data = pd.read_csv("Data.csv")
data

   Country   Age   Salary Purchased
0   France  44.0  72000.0       Yes
1    Spain  27.0  48000.0       Yes
2      NaN  30.0  54000.0       NaN
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### 1. Removing Rows

In [73]:
df = data.dropna()
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0       Yes
1    Spain  27.0  48000.0       Yes
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### 2. Imputers

In [82]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

In [95]:
data.iloc[:, 1:3].values #Taking Age and Salary values

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [96]:
x = imputer.fit_transform(data.iloc[:, 1:3].values) #Transforming Age and Salary values with Mean
x

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [97]:
data.iloc[:, 1:3] = x #Putting Transformed data back to dataset
data

   Country        Age        Salary Purchased
0   France  44.000000  72000.000000       Yes
1    Spain  27.000000  48000.000000       Yes
2      NaN  30.000000  54000.000000       NaN
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

## Handling Null Values - Categorical

### 1. Imputers

In [104]:
imputer = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
x = imputer.fit_transform(data.iloc[:, :].values)
data.iloc[:, :] = x #Putting Transformed data back to dataset
data

   Country   Age   Salary Purchased
0   France  44.0  72000.0       Yes
1    Spain  27.0  48000.0       Yes
2   France  30.0  54000.0       Yes
3    Spain  38.0  61000.0        No
4  Germany  40.0  48000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  27.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

## Removing Null Values from Google Playstore Dataset

In [14]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [172]:
df = pd.read_csv("googleplaystore.csv")
df.head()
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [173]:
# Rating column has large number of null values. using dropna() deletes almost 15% of the data which might give error while analysing data. To overcome this problem, using imputer here.

In [174]:
impute = SimpleImputer(missing_values = np.nan, strategy='mean')
x = impute.fit_transform(df.iloc[:,2:3].values)
df.iloc[:,2:3] = x
df.head()
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
Genres            0
Last Updated      0
Current Ver       8
Android Ver       3
dtype: int64

In [201]:
# For remaining null values, dropping them as they are less in number
df = df.dropna()
df.isnull().sum()
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,4.193338,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

## Data Analysis for Multiple Columns

In [176]:
df.head()
df.values.shape
df = df.values

### 1. How many free Apps are there in ART_AND_DESIGN ?

In [177]:
count = 0
for data in df:
    if data[1]=='ART_AND_DESIGN' and data[6]=='Free':
        count += 1
print("There are", count, "free apps in ART_AND_DESIGN")

There are 61 free apps in ART_AND_DESIGN

### 2. How many apps in ART_AND_DESIGN with Rating more than 4.5 ?

In [178]:
count = 0

for data in df:
    if data[1]=="ART_AND_DESIGN" and data[2] > 4.5:
        count += 1

print("There are",count, "apps with rating greater than 4.5")

There are 22 apps with rating greater than 4.5

### 3. How many Apps in FAMILY Category are Free with Rating more than 4.5 ?

In [179]:
count = 0 
for data in df:
    if data[1]=="FAMILY" and data[2]>4.5 and data[6]=="Free":
        count += 1

print("There are", count, "Free apps in FAMILY Category with Rating more than 4.5")

There are 314 Free apps in FAMILY Category with Rating more than 4.5

### 4. List all Free apps in FAMILY Category with Rating more than 4.5

In [180]:
apps = []

for data in df:
    if data[1] == "FAMILY" and data[2] > 4.5 and data[6] == "Free":
        apps.append(data[0])

print(apps)

['Super ABC! Learning games for kids! Preschool apps', 'Candy Pop Story', 'Dog Run - Pet Dog Simulator', 'Puzzle Kids - Animals Shapes and Jigsaw Puzzles', 'No. Color - Color by Number, Number Coloring', 'Garden Fruit Legend', 'Piano Kids - Music & Songs', 'Duolingo: Learn Languages Free', 'Super ABC! Learning games for kids! Preschool apps', 'Drawing for Kids Learning Games for Toddlers age 3', 'Baby ABC in box! Kids alphabet games for toddlers!', 'Henry Danger Crime Warp', 'Fruit Cube Blast', 'Toddler Kids Puzzles PUZZINGO', 'Fuzzy Seasons: Animal Forest', 'Dog Run - Pet Dog Simulator', 'My Oasis - Calming and Relaxing Idle Clicker Game', 'Ninja Dash - Ronin Jump RPG', 'Monster High™ Minis Mania', 'Monica Toy TV', 'Sworkit Kids - Fitness Meets Fun', 'Crazy Colors: Bubbles Matching', 'Pino chess', 'Duolingo: Learn Languages Free', 'Animal Jam - Play Wild!', 'Dog Sim Online: Raise a Family', 'Color by Number - Draw Sandbox Pixel Art', 'Build a Bridge!', 'Find a Way: Addictive Puzzle', 'CompTIA Exam Training', 'Gymnastics Superstar - Spin your way to gold!', 'Hungry Hearts Diner: A Tale of Star-Crossed Souls', 'Dragon Sim Online: Be A Dragon', 'Cat Sim Online: Play with Cats', 'Clash of Clans', 'Clash Royale', 'Learn C++', 'C Programming Zone', 'All C Programs', 'codeEazy - C/C++/JAVA', 'C Functions', 'Learn Basic C - For Beginners', 'C Prowess', '101 C Programming Problems', 'C BOOK-C PROGRAMS', 'Eternium', 'Harris J Lyrics', '2048 BTS J Hope KPop Puzzle Game', 'J. Cole Albums (2007-2017)', 'K-Otic Universe', 'CASE K-12 Math English Science', 'K-Spapp, the K-Space app', 'EXO-L', "Fantastic Chefs: Match 'n Cook", 'Twitch: Livestream Multiplayer Games & Esports', 'Channel U', 'Get Free V-bucks_fortnite Hints', 'Easy V-Bux free', 'X-Wing Squadron Builder', 'JW Caleb y Sofia', "PewDiePie's Tuber Simulator", 'Z-Empire: Dead Strike', 'Angry Birds Blast', 'Angry Birds Match', 'Angry Birds 2', 'Alchemy Classic Ad Free', 'Nasihat - Chalo ae Pyaara', '9GAG: Funny Gifs, Pics, Memes & Videos for IGTV', 'Orbita AI — Exciting mobile puzzles & riddles', 'Learn Artificial Intelligence', 'Animal Jam - Play Wild!', 'AJ Official', 'Little Pets Animal Guardians', 'AJ Rafael Music Lessons', 'Weapon stripping 3D', 'Al jazeera TV', 'Al Quran Audio (Full 30 Juz)', 'Quran for All (Al-Huda Int.)', 'Ayat - Al Quran', 'Quran Juz-30 - Mahad al Zahra', 'Al Quran MP3 - Quran Reading®', 'Al-Quran Ahmad Saud Offline', 'Virtual lover', 'virtual lover 3D', 'Bubbu – My Virtual Pet', 'AP® Guide', 'AP Mobile', 'Study AP World History', 'AP Chemistry Prep: Practice Tests and Flashcards', 'AP World History: Practice Tests and Flashcards', 'AP Biology Prep: Practice Tests, Flashcards', 'AP European History: Practice Tests and Flashcards', 'Adventure Quest World Mobile Quiz', 'AQ Ria Retail', 'Accounting Quiz (AQ) Malaysia', "Wowkwis aq Ka'qaquj", 'Questland: Turn Based RPG', 'Grow Stone Online : 2d pixel RPG, MMORPG game', 'Egg, Inc.', 'Choices: Stories You Play', 'Aw Restaurant', 'AW Training', 'Anime Expo 2018', 'INTERACTIVE CALCULUS FOR MATHS AND PHYSICS', 'Pinoy Kid Song Ako ay may Lobo', 'Quran Khmer Offline AY', 'Permit Test AZ Arizona MVD DOT', 'Catalyst AZ', 'Az Video Status', 'Goody.ba', 'Learn alif ba ta', 'Arabic Alphabet Alif Ba Ta Wooden Blocks', "Let's Learn Alif Ba Ta", 'Sufara.ba', 'Elif Ba - Learn The Holy Quran', 'Elifba Quran Learning Game', 'Railroad Radio Vancouver BC', 'BD Online Passport Application', "BD Hospital's", 'Exam Result BD', 'BG Future School', 'Learn Bulgarian Free', 'Bh Public School', 'BH Challenge - Museum of the Jewish People', 'Bitmoji – Your Personal Emoji', 'Business Intelligence & Data', 'TED', 'English Grammar Test', 'HON. B.J. ACS COLLEGE ALE', 'BK Video Status', 'Audio Murli Glossary For BK', "Baba Yaad Hai?(BK's)", 'BK murli today (Mobile Murli) - Gyan', 'BK Murli Dictionary (H to E)', 'BkEmu - BK-0010/11M emulator', 'Cerulean Heart', 'あなカレ【BL】無料ゲーム', 'BM SPM Practice', 'Township', 'Blood Pressure Diary', 'RoboPad', 'Br Shafi', 'Companion for Fortnite & Fortnite Battle Royale', 'Vlogger Go Viral - Tuber Game', 'Loved by King Bs', 'BS CS IT & SE', 'Marked by King Bs', 'COMSATS BOOK STORE FOR BS(CS)', 'Beauty Rental Shop', 'Sleeping Delivery', 'Wifi BT Scanner', 'BU Study', 'Barisal University App-BU Face', "BU Students' Rep. Council", 'BU Calculator', 'BV Sridhara Maharaj', 'Quadratic Equation Solver with Steps and Graphs', 'Sandbox - Color by Number Coloring Pages', 'Sandbox Art-Sandbox Color by Number Coloring Pages', 'Color By Number - Sandbox Pixel Coloring Book', 'PixelDot - Color by Number Sandbox Pixel Art', 'PixPanda - Color by Number Pixel Art Coloring Book', 'Pixyfy: coloring by number coloring book', 'Draw Color by Number - Sandbox Pixel Art', 'Butterfly Pixel Art - coloring by number', 'Color by Number: Pixel Art', 'UNICORN - Color By Number & Pixel Art Coloring', 'FunnyPixels - Color by number Sandbox', 'No.Diamond – Colors by Number', 'Park Limousine: Realistic Limo Parking Simulator', 'CB News', 'CB Register', 'CD CHOICE TUBE', 'Yazdani Cd Center EllahAbad Official App', 'MCQ CE IT', 'Magana Jari ce Littafi Na Uku : Part 3 of 3', 'CF Life', 'All Info about Cg', 'CG FM', 'CG - Chemistry free', 'CG Jobs', 'BF CG Abstract Pictures', 'CI Dictionary', 'Sir C J New Primary School', 'Louis CK', 'Tic Tac CK', 'Castle Clash: Heroes of the Empire US', 'Cartoon Network Match Land', 'Super Slime Blitz - Gumball', 'Surely You Quest - Magiswords', 'We Bare Bears Match3 Repairs', 'Champions and Challengers - Adventure Time', 'CN Resident', 'CP Channel', 'Foothills CP', 'Cp Calculator for Evolution:GO', 'ClanManagerTT2', 'Christian Questions Podcast', 'CR & CoC Private Server - Clash Barbarians PRO', 'Ultimate Clash Royale Tracker', 'Servidor Privado de CR y CoC - Light Royale', 'Deck Shop for Clash Royale', 'Cr Aviation Academy', 'CS Interview Questions (TechQ)', 'DU CS Lectures - Learn to Code for Free', 'CS & IT Interview Questions', 'CA CS Network', 'CT Scan Generations', 'CT Brain Interpretation', 'Permit Test Connecticut CT DMV', 'Cy-Reader', 'MadLipz', 'DB Tools', 'DB for Hustle Castle', 'MARVEL Future Fight', 'DC N COMPANY ENTERTAINMENT RADIO!', "Driver Permit Test Prep DC DMV Driver's License Ed", 'Coloring Book for Me & Mandala', 'Anime Love Story Games: ✨Shadowtime✨', 'DH-UFO', 'Idle Heroes', 'Duolingo: Learn Languages Free', 'PK and DK Audio App', 'dk', 'Account Class-12 Solutions (D K Goel) Vol-2', 'DL Hughley', 'DM Buddy » Learn Digital Marketing', 'Disciple Maker’s (DM) Lab', 'DN Employee', 'Dragon Nest M', 'CritDice - Dice Roller', 'Maher EL Mouaikly - Offline', 'Darkness Rises', 'Latest DP and Status Pro 2018', 'Faceoff DP Battle App', 'RPG Dragon Lapis', 'DQSalmaan - A fan made App', 'DS', 'MegaN64 (N64 Emulator)', 'DS-Students', 'DT Driving Test Theory', 'WPBS-DT', 'Du Chinese – Mandarin Lessons', 'DV ASSIST', 'DV Lottery Simulator', 'DV-2019 UK/British', 'DW Audio', 'German Listening', 'Piczle Lines DX', 'DX Simulation for OOO Dx Belt', 'DX Simulation for Kabuto Henshin Belt 2018', 'DX Simulation for Double Dx Henshin Belt 2018', 'KPS CHAUHAN DY/DX', 'DYPSOET', 'Typical EA Game', 'EC Calgary', 'EC Fairgrounds', 'GATE Syllabus for EC 2018 & Notifications', 'English Conversation Courses', 'Dance Magic Fashion Style Games', 'EI国际', 'TeamWard – live help for LoL', 'Master E.K', 'Ek Onkar', 'Pyaar Ek Dhoka', 'Ek Bander Ne Kholi Dukan', 'Toilet Ek Prem Katha Songs Lyrics in Hindi', 'Sanu Ek Pal Chain Song Videos - RAID Movie Songs', 'Ek Qissa He Quran Se (Qurani Waqiyat)', 'Lyrics of Ek Paheli Leela', 'Exiled Kingdoms RPG', 'Shabad Gurubani Punjabi mp3 free - Ek Onkar Satnam', 'El Falı', 'OWLIE BOO', 'Narcos: Cartel Wars', 'Hello English: Learn English', 'Learn Top 300 English Words', 'Masha and the Bear. Games for kids', 'Masha and The Bear Jam Day Match 3 games for kids', 'Masha and the Bear: Good Night!', 'EP Radio', 'Super Doctor 2 - My Newborn Baby ER Injection', 'Open Heart Surgery Hospital ER: Crazy Doctor Sim', 'YEBIS OpenGL ES 3.0 Tech Demo', 'Advanced calculator fx 991 es plus & 991 ms plus', 'Castle Clash: Epic Empire ES', 'School scientific calculator fx 500 es plus 500 ms', "Lettre et demande d'emploi", 'daskal.eu', 'PokeType - Dex', 'Pink Guy - Ey B0ss', 'Ey Sey Storytime រឿងនិទានតាឥសី', 'Fallout Shelter', 'Story Time FD', 'FD VR Music Videos - MTV Pop and Rap in 360', 'Fire Emblem Heroes', 'Safe Santa Fe', 'POLARIS 2MFG', 'Puzzles Volvo FH 16 Trucks', 'Jigsaw Volvo FH 16 Trucks', 'FH School', 'FK Željezničar Izzy', 'Permit Test FL Florida DHSMV', 'FL Lottery Results', 'Scratch-Off Guide for FL Lotto', 'Canvas FL', 'Florida Wildflowers', 'How it Works: FN SCAR assault rifle', 'Ninja FN Button', 'Pin-fo', 'Fr Ignacio Outreach', 'Castle Clash: RPG War and Strategy FR', 'Fr. Daoud Lamei', 'Fr. Mike Schmitz Audio Teachings']

## Data Analysis Using Conditions

In [15]:
df = pd.read_csv("googleplaystore.csv")
impute = SimpleImputer(missing_values = np.nan, strategy='mean')
x = impute.fit_transform(df.iloc[:,2:3].values)
df.iloc[:,2:3] = x
df = df.dropna()
df.isnull().sum()
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,4.193338,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [189]:
df['Category']=='ART_AND_DESIGN' #Displays rows with Category ART_AND_DESIGN as True else False

0         True
1         True
2         True
3         True
4         True
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Name: Category, Length: 10829, dtype: bool

In [191]:
df[df['Category']=='ART_AND_DESIGN'] #Displays all rows with Category ART_AND_DESIGN

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7174,Easy DIY CD Craft Ideas,ART_AND_DESIGN,4.193338,7,5.6M,"5,000+",Free,0,Everyone,Art & Design,"May 30, 2018",1.0,2.3 and up
8679,Dp for girls,ART_AND_DESIGN,4.200000,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.300000,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8871,Test Application DT 02,ART_AND_DESIGN,4.193338,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.000000,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

### 1. How many Free Apps are there in ART_AND_DESIGN Category?

In [192]:
df_pr = df[df['Category']=='ART_AND_DESIGN']
df_pr[df_pr['Type']=='Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7174,Easy DIY CD Craft Ideas,ART_AND_DESIGN,4.193338,7,5.6M,"5,000+",Free,0,Everyone,Art & Design,"May 30, 2018",1.0,2.3 and up
8679,Dp for girls,ART_AND_DESIGN,4.200000,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.300000,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8871,Test Application DT 02,ART_AND_DESIGN,4.193338,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.000000,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

### 2. How many Apps in ART_AND_DESIGN Category with Rating more than 4.5?

In [195]:
df_pr = df[df['Category']=='ART_AND_DESIGN']
df_pr[df_pr['Rating'] > 4.5]
len(df_pr[df_pr['Rating'] > 4.5])

22

### 3. How many Free Apps in FAMILY Category with Rating more than 4.5?

In [200]:
df_pr = df[df['Category']=='FAMILY']
df_rating = df_pr[df_pr['Rating'] > 4.5]
df_rating[df_rating["Type"] == "Free"]['App']

2020     Super ABC! Learning games for kids! Preschool ...
2023                                       Candy Pop Story
2029                           Dog Run - Pet Dog Simulator
2032       Puzzle Kids - Animals Shapes and Jigsaw Puzzles
2040          No. Color - Color by Number, Number Coloring
                               ...
10691                                               Pin-fo
10801                                  Fr Ignacio Outreach
10809                Castle Clash: RPG War and Strategy FR
10820                                      Fr. Daoud Lamei
10837                     Fr. Mike Schmitz Audio Teachings
Name: App, Length: 314, dtype: object

## GroupBy in Pandas

### 1. Name apps that are in ART_AND_DESIGN Category and Rating more than 4.5 in ascending order of their Ratings.

In [17]:
df_pr = df[df['Category'] == "ART_AND_DESIGN"]
df_pr = df_pr[df_pr["Rating"] > 4.5]
df_pr.sort_values(by = "Rating", ascending = True)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
4764,X Launcher Prime: With OS Style Theme & No Ads,ART_AND_DESIGN,4.7,149,3.5M,"1,000+",Paid,$1.99,Everyone,Art & Design,"July 30, 2018",1.2.2,4.1 and up
4755,"X Launcher Pro: PhoneX Theme, OS11 Control Center",ART_AND_DESIGN,4.7,801,3.5M,"5,000+",Paid,$1.99,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
4749,X Launcher: With OS11 Style Theme & Control Ce...,ART_AND_DESIGN,4.7,5754,4.4M,"100,000+",Free,0,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
45,"Canva: Poster, banner, card maker & graphic de...",ART_AND_DESIGN,4.7,174531,24M,"10,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.6.1,4.1 and up
38,PIP Camera - PIP Collage Maker,ART_AND_DESIGN,4.7,158,11M,"10,000+",Free,0,Everyone,Art & Design,"November 29, 2017",1.3,4.0.3 and up
36,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"August 2, 2018",1.0.9,4.4 and up
26,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up
24,HD Mickey Minnie Wallpapers,ART_AND_DESIGN,4.7,118,23M,"50,000+",Free,0,Everyone,Art & Design,"July 7, 2018",1.1.3,4.1 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,"July 12, 2018",2.2.6.2,4.0.3 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
34,I Creative Idea,ART_AND_DESIGN,4.7,353,4.2M,"10,000+",Free,0,Teen,Art & Design,"April 27, 2018",1.6,4.1 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,"April 25, 2018",1.5,3.0 and up
3982,Cardi B Wallpaper,ART_AND_DESIGN,4.8,253,3.7M,"50,000+",Free,0,Everyone,Art & Design,"November 1, 2017",1.0.0,4.0 and up
4759,X Launcher Pro - IOS Style Theme & Control Center,ART_AND_DESIGN,4.8,1216,8.6M,"10,000+",Paid,$1.99,Everyone,Art & Design,"June 26, 2018",1.0.0,4.1 and up
5254,AJ Styles HD Wallpapers,ART_AND_DESIGN,4.8,48,25M,"5,000+",Free,0,Everyone,Art & Design,"August 4, 2018",1.1.1,4.1 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

### 2. Name apps that are in ART_AND_DESIGN Category in descending order of their Reviews.

In [12]:
df_pr = df[df['Category'] == "ART_AND_DESIGN"]
df_pr.sort_values(by = "Reviews", ascending = False)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
11,Name Art Photo Editor - Focus n Filters,ART_AND_DESIGN,4.400000,8788,12M,"1,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.0.15,4.0 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
47,Little Teddy Bear Colouring Book Game,ART_AND_DESIGN,4.200000,85,8.0M,"100,000+",Free,0,Everyone,Art & Design,"December 17, 2017",2.0.0,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,Pink Silver Bow Keyboard Theme,ART_AND_DESIGN,4.200000,1120,9.2M,"100,000+",Free,0,Everyone,Art & Design,"July 12, 2018",6.7.12.2018,4.0.3 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.600000,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up
33,Easy Origami Ideas,ART_AND_DESIGN,4.200000,1015,11M,"100,000+",Free,0,Everyone,Art & Design,"January 6, 2018",1.1.0,4.1 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.000000,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up
8871,Test Application DT 02,ART_AND_DESIGN,4.193338,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up

### 3. Which Category is having maximum average Rating?

In [30]:
df.groupby('Category')['Rating'].mean().sort_values(ascending=False)

Category
EDUCATION              4.387778
ART_AND_DESIGN         4.368438
EVENTS                 4.363647
BOOKS_AND_REFERENCE    4.311537
PERSONALIZATION        4.306873
GAME                   4.282506
PARENTING              4.282223
HEALTH_AND_FITNESS     4.266296
BEAUTY                 4.260882
SHOPPING               4.254052
SOCIAL                 4.248001
WEATHER                4.239675
SPORTS                 4.218404
PRODUCTIVITY           4.208287
HOUSE_AND_HOME         4.196819
FAMILY                 4.192490
PHOTOGRAPHY            4.192179
AUTO_AND_VEHICLES      4.190824
MEDICAL                4.190167
LIBRARIES_AND_DEMO     4.182938
FOOD_AND_DRINK         4.170709
COMMUNICATION          4.163842
COMICS                 4.156445
BUSINESS               4.145987
NEWS_AND_MAGAZINES     4.142993
FINANCE                4.139108
ENTERTAINMENT          4.126174
TRAVEL_AND_LOCAL       4.119716
LIFESTYLE              4.112427
VIDEO_PLAYERS          4.074858
TOOLS                  4.065970
MAPS_AND_NAVIGATION    4.065061
DATING                 4.007864
Name: Rating, dtype: float64

### 4. Count Number of Apps in each Category in descending Order.

In [32]:
df.groupby('Category')['Type'].count().sort_values(ascending=False)

Category
FAMILY                 1968
GAME                   1144
TOOLS                   841
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         390
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     230
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       84
WEATHER                  82
EVENTS                   64
ART_AND_DESIGN           64
PARENTING                60
COMICS                   60
BEAUTY                   53
Name: Type, dtype: int64

### 5. How many Free Apps are there in each Category?

In [34]:
df_pr = df[df['Type'] == 'Free']
df_pr.groupby('Category')['Type'].count().sort_values(ascending=False)

Category
FAMILY                 1778
GAME                   1061
TOOLS                   764
BUSINESS                446
PRODUCTIVITY            396
LIFESTYLE               363
SPORTS                  360
COMMUNICATION           360
MEDICAL                 354
FINANCE                 349
HEALTH_AND_FITNESS      325
PHOTOGRAPHY             313
PERSONALIZATION         308
SOCIAL                  292
NEWS_AND_MAGAZINES      281
SHOPPING                258
TRAVEL_AND_LOCAL        246
DATING                  227
BOOKS_AND_REFERENCE     202
VIDEO_PLAYERS           171
EDUCATION               152
ENTERTAINMENT           147
MAPS_AND_NAVIGATION     132
FOOD_AND_DRINK          125
HOUSE_AND_HOME           88
LIBRARIES_AND_DEMO       83
AUTO_AND_VEHICLES        82
WEATHER                  74
EVENTS                   63
ART_AND_DESIGN           61
COMICS                   60
PARENTING                58
BEAUTY                   53
Name: Type, dtype: int64